### ISSUE TITLE
use_default_workloads missing  Synthetic_Generator_Type

### ISSUE THREAD

**Issue by c-w-m** [CMU-SAFARI/MQSim#2] opened 2018-05-14 18:43 UTC
ERROR:Unhandled request type generator in FTL preconditioning function when running with on-the-fly generated workload (i.e., default_ssdconfig.xml and default_workload.xml don't exist initially so they are generated by MQSim)
commandline: 
./MQSim -i default_ssdconfig.xml -w default_workload.xml

**Comment by c-w-m** [comment] 2018-05-14 18:45
suggestion
file: main.cpp
line 172 and 204, insert:
		io_flow_1->Synthetic_Generator_Type = Utils::Request_Generator_Type::BANDWIDTH;

**Comment by arashta** [comment] 2018-05-15 17:39
Hi Craig,

Thanks for the feedback. The issue is resolved in the latest commit. MQSim now generates a correct sample input file.

**Closed** 2018-05-16 13:51 UTC
